# https://rubocop.readthedocs.io/en/stable/
require:
  - rubocop-md
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

# Exclusions
AllCops:
  Exclude:
    - bin/bundle
    - db/schema.rb
    - node_modules/**/*

# Preferences
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Asked by rubocop
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
